# Generated by Django 3.2.8 on 2022-01-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='музыка атауы')),
                ('music', models.FileField(upload_to='audio/', verbose_name='музыка файлы')),
                ('views', models.IntegerField(default=0, verbose_name='есту саны')),
            ],
            options={
                'verbose_name': 'музыка',
                'verbose_name_plural': 'музыкалар',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='жанр атауы')),
            ],
            options={
                'verbose_name': 'музыка жанр',
                'verbose_name_plural': 'музыка жанрлары',
                'db_table': 'music_type',
            },
        ),
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайктар',
                'db_table': 'music_like',
            },
        ),
        migrations.CreateModel(
            name='MusicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='пікір')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'пікір',
                'verbose_name_plural': 'пікірлер',
                'db_table': 'music_comment',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.ManyToManyField(related_name='music_types', to='music.MusicType', verbose_name='мазыка жанры'),
        ),
    ]
