# Generated by Django 3.2.8 on 2022-01-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='альбом атауы')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img/music/album-cover/', verbose_name='альбом суреті')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомдар',
                'db_table': 'music_album',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='музыка атауы')),
                ('music', models.FileField(upload_to='audio/', verbose_name='музыка файлы')),
                ('views', models.IntegerField(default=0, verbose_name='есту саны')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='құрылған уақыт')),
                ('auhtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='авторы')),
            ],
            options={
                'verbose_name': 'музыка',
                'verbose_name_plural': 'музыкалар',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='жанр атауы')),
            ],
            options={
                'verbose_name': 'музыка жанр',
                'verbose_name_plural': 'музыка жанрлары',
                'db_table': 'music_type',
            },
        ),
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайктар',
                'db_table': 'music_like',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.ManyToManyField(related_name='music_types', to='music.MusicType', verbose_name='мазыка жанры'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='таңдаулар атауы')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='құрылған уақыт')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='құрушы')),
            ],
            options={
                'verbose_name': 'таңдаулар',
                'verbose_name_plural': 'таңдаулар',
                'db_table': 'music_favorites',
            },
        ),
        migrations.CreateModel(
            name='FavoriteMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.favorites', verbose_name='таңдаулар')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
            ],
            options={
                'verbose_name': 'таңдаулардағы музыка',
                'verbose_name_plural': 'таңдаулардағы музыкалар',
                'db_table': 'favorites_music',
            },
        ),
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='пікір')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'пікір',
                'verbose_name_plural': 'пікірлер',
                'db_table': 'album_comment',
            },
        ),
    ]
