# Generated by Django 3.2.8 on 2021-10-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='жанр атауы')),
            ],
            options={
                'verbose_name': 'музыка жанр',
                'verbose_name_plural': 'музыка жанрлары',
                'db_table': 'music_type',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='музыка атауы')),
                ('music', models.FileField(upload_to='audio/', verbose_name='музыка файлы')),
                ('music_type', models.ManyToManyField(related_name='music_types', to='music.MusicType', verbose_name='мазыка жанры')),
            ],
            options={
                'verbose_name': 'музыка',
                'verbose_name_plural': 'музыкалар',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='пікір')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пайдаланушы')),
            ],
            options={
                'verbose_name': 'пікір',
                'verbose_name_plural': 'пікірлер',
                'db_table': 'comment',
            },
        ),
    ]
