# Generated by Django 3.2.8 on 2021-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='like',
            field=models.IntegerField(default=0, verbose_name='лайк саны'),
        ),
        migrations.AddField(
            model_name='music',
            name='views',
            field=models.IntegerField(default=0, verbose_name='есту саны'),
        ),
    ]
