# Generated by Django 3.2.8 on 2022-02-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='альбум')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='музыка')),
            ],
            options={
                'verbose_name': 'альбумдағы музыка',
                'verbose_name_plural': 'альбумдағы музыкалар',
                'db_table': 'album_music',
            },
        ),
    ]
