# Generated by Django 3.2.8 on 2022-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_albummusic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='auhtor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='music',
            name='music_type',
            field=models.ManyToManyField(related_name='music_types', to='music.MusicType', verbose_name='музыка жанры'),
        ),
        migrations.AlterField(
            model_name='musictype',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='жанр атауы'),
        ),
    ]
