# Generated by Django 3.2.8 on 2022-01-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
        ('music', '0002_music_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='auhtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='авторы'),
        ),
    ]
