# Generated by Django 3.2.8 on 2022-02-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20220220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=24, verbose_name='альбом атауы'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='name',
            field=models.CharField(max_length=24, verbose_name='таңдаулар атауы'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=24, verbose_name='музыка атауы'),
        ),
        migrations.AlterField(
            model_name='musictype',
            name='name',
            field=models.CharField(max_length=24, unique=True, verbose_name='жанр атауы'),
        ),
    ]
