# Generated by Django 3.2.8 on 2022-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user_2022011922', max_length=24, verbose_name='атау')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='телефон нөмер')),
                ('password', models.CharField(max_length=60, verbose_name='құпия сөз')),
                ('is_admin', models.BooleanField(default=False, verbose_name='админ')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='туған күн')),
                ('gender', models.BooleanField(choices=[(True, 'Ер'), (False, 'Әйел')], default=0, verbose_name='жыныс')),
                ('avatar', models.ImageField(default='img/user/avatar/default-avatar.png', upload_to='img/user/avatar/', verbose_name='аватар')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='құрылған уақыт')),
            ],
            options={
                'verbose_name': 'пайдаланушы',
                'verbose_name_plural': 'пайдаланушылар',
                'db_table': 'user',
            },
        ),
    ]
