# Generated by Django 3.2.8 on 2021-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пайдаланушы', 'verbose_name_plural': 'пайдаланушылар'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='туған күн'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Ер'), (False, 'Әйел')], default=True, verbose_name='Жыныс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/user/avatar/default-avatar.png', upload_to='img/user/avatar/', verbose_name='аватар'),
        ),
    ]
