# Generated by Django 3.2.8 on 2022-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_2022012012', max_length=24, verbose_name='атау'),
        ),
    ]
