# Generated by Django 3.2.8 on 2022-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_2022020623', max_length=24, verbose_name='атау'),
        ),
    ]
