# Generated by Django 3.2.8 on 2022-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='құпия сөз'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_2022022015', max_length=24, verbose_name='атау'),
        ),
    ]
